image:
  file: .gitpod.Dockerfile

# This will expose all necessary ports needed for your VNC image
ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: pip3 install -r requirements.txt
    command: clear && dagit
    name: Split terminal
  - openMode: split-right
    command: echo SplitTerminal && clear
